server:
  port: 8080
  servlet:
    session:
      timeout: 1800
mybatis:
  config: mybatis-config.xml
  mapper-locations: mybatis/mapper/UserMapper.xml

spring:
  datasource: 
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: 123456
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

    
file:
  dir:C:\Dev\image
  